export const SET_TOKEN = 'SET_TOKEN'
export const SET_NAME = 'SET_NAME'
export const SET_NICKNAME = 'SET_NICKNAME'
export const SET_AVATAR = 'SET_AVATAR'
export const SET_ROLES = 'SET_ROLES'
export const SET_INTRODUCTION = 'SET_INTRODUCTION'
export const SET_USERINFO = 'SET_USERINFO'
